source "https://rubygems.org"

group :test do
  gem 'rails', '3.0.0.rc'
  gem "rspec-rails"
  gem "cucumber-rails"
  gem "capybara"
  gem 'cucumber', '~> 4.0.0.rc.1'
  gem 'selenium-webdriver'
  gem 'poltergeist'
  gem 'calabash-android'
end